[font]
size = 16.0
[font.normal]
family = "Iosevka NF"
style = "Regular"
[font.bold]
family = "Iosevka NF"
style = "Bold"
[font.italic]
family = "Iosevka NF"
style = "Italic"
[font.bold_italic]
family = "Iosevka NF"
style = "Italic"

[window]
opacity = 0.7
